### ISSUE TITLE
使用 chrome 但 Lyricify 没有检测到授权

### ISSUE THREAD

**Issue by Ciaory** [WXRIW/Lyricify-App#121]
![image](https://user-images.githubusercontent.com/99544424/217132338-e35f8c76-ab38-4cef-b02e-cc00aeb63fdc.png)

**Comment by WXRIW** [comment]
换一个默认浏览器试试看，这个情况我也没遇到过😂

**Comment by Ciaory** [comment]
edge试了一下，也是这种情况😥

**Comment by Potato009** [comment]
@Ciaory 那就换个非chromium内核的

**Comment by WXRIW** [comment]
@Ciaory 可能是其他原因造成的，我到时候加一个手动输入token的方式即可，你目前可以试试其他电脑上可不可以登录

**Comment by Ciaory** [comment]
> @Ciaory 那就换个非chromium内核的

在Opera下尝试授权，没有成功

**Comment by Potato009** [comment]
@Ciaory 😓换火狐之类的，另外记住opera用的还是chromium

**Comment by WXRIW** [comment]
@Potato009 目前判断跟浏览器关系不大，可以尝试在其他电脑上完成登录，然后把配置文件复制到这台电脑上  
%appdata%/lyricify/lyricify for spotify/accounts.json

**Comment by Ciaory** [comment]
> @Potato009 目前判断跟浏览器关系不大，可以尝试在其他电脑上完成登录，然后把配置文件复制到这台电脑上 %appdata%/lyricify/lyricify for spotify/accounts.json

@WXRIW 现在换了个电脑可以了🙏

日志文件：
```2023-02-07T09:37:12.2868714+08:00 [Event] App starting, version 4.0.3.230201-release
2023-02-07T09:37:12.4286460+08:00 [Event] Showing Welcome Window
2023-02-07T09:37:45.7501296+08:00 [Error] System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (由于目标计算机积极拒绝，无法连接。 (127.0.0.1:1080))
 ---> System.Net.Http.HttpRequestException: 由于目标计算机积极拒绝，无法连接。 (127.0.0.1:1080)
 ---> System.Net.Sockets.SocketException (10061): 由于目标计算机积极拒绝，无法连接。
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.EstablishProxyTunnelAsync(Boolean async, HttpRequestHeaders headers, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at SpotifyAPI.Web.Http.NetHttpClient.DoRequest(IRequest request, CancellationToken cancel)
   at SpotifyAPI.Web.Http.APIConnector.DoRequest(IRequest request, CancellationToken cancel)
   at SpotifyAPI.Web.Http.APIConnector.DoSerializedRequest[T](IRequest request, CancellationToken cancel)
   at SpotifyAPI.Web.Http.APIConnector.SendAPIRequest[T](Uri uri, HttpMethod method, IDictionary`2 parameters, Object body, IDictionary`2 headers, CancellationToken cancel)
   at Lyricify_for_Spotify.Windows.WelcomeWindow.VPWGvJE8lk(Object  , AuthorizationCodeResponse  )
   --- End of inner exception stack trace ---
```

**Comment by Ciaory** [comment]
> @Ciaory 😓换火狐之类的，另外记住opera用的还是chromium

好的好的 @Potato009

**Comment by WXRIW** [comment]
此 Issue 关闭，后期将加入手动输入授权的方式
