### ISSUE TITLE
无法获取歌词

### ISSUE THREAD

**Issue by ixcmstudio** [WXRIW/Lyricify-App#128]
版本：v4.0.7-release
在使用软件时部分不能获取到歌词，但是Lyricify3可以正常获取到
网络环境：纯外网，可以正常访问http://e.wxriw.cn/
尝试在设置中勾选不在 Lyricify 服务器请求中使用代理，切换歌词为网易云音乐优先，但是依然无法获取到歌词
使用国内的网时不能正常获取歌词的歌曲可以正常获取歌曲，但是由于环境问题我大部分时间只能使用外网，希望了解一下这是什么问题
使用外网

![图片](https://user-images.githubusercontent.com/73055677/224261852-b10343fd-c539-4a73-8ce4-64524cf7e6bd.png)

使用国内网络
![图片](https://user-images.githubusercontent.com/73055677/224263370-fd987ce1-ff22-4070-bcf2-80e15aa8c198.png)

**Comment by WXRIW** [comment]
具体情况我也不清楚，你把Log.Lyrics.txt发给我看一下

**Comment by WXRIW** [comment]
长时间没有回复，故关闭此 Issue

**Comment by waitfortea** [comment]
2023-08-02T12:29:30.3559483+08:00 [Trace] User info updated
2023-08-02T12:29:30.9745739+08:00 [Trace] Updated playback info
2023-08-02T12:29:31.0533857+08:00 [Error] System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (An error occurred while sending the request.)
 ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Lyricify_for_Spotify.App.<>c__DisplayClass26_0.fTU2NjWWse8V2Yv5KPll.MoveNext()
   --- End of inner exception stack trace ---
2023-08-02T12:29:31.2281675+08:00 [Event] MainWindow loaded
2023-08-02T12:29:57.8676319+08:00 [Event] MainWindow Closing
2023-08-02T12:29:57.8711414+08:00 [Event] App exiting, version 4.1.4.230614-release
2023-08-02T12:30:03.7063151+08:00 [Event] App starting, version 4.1.4.230614-release
2023-08-02T12:30:03.9019418+08:00 [Event] Spotify Refresh Token found
2023-08-02T12:30:03.9168693+08:00 [Event] Logged in to Spotify account
2023-08-02T12:30:03.9173307+08:00 [Event] Finished App loading
2023-08-02T12:30:04.3662255+08:00 [Event] Loading MainWindow
2023-08-02T12:30:04.4007115+08:00 [Trace] Settings loaded
2023-08-02T12:30:06.3766795+08:00 [Error] APITooManyRequestsException - Retry after: 22
2023-08-02T12:30:06.3769895+08:00 [Error] Failed to update user info
2023-08-02T12:30:28.6219820+08:00 [Error] APITooManyRequestsException - Retry after: 1
2023-08-02T12:30:28.8611596+08:00 [Error] APITooManyRequestsException - Retry after: 1
2023-08-02T12:30:30.2698106+08:00 [Trace] User info updated
2023-08-02T12:30:30.6096388+08:00 [Trace] Updated playback info
2023-08-02T12:30:30.8592739+08:00 [Event] MainWindow loaded



主机可以正常上外网，开的全局，但是无法获取歌曲信心，3.8可以

**Comment by WXRIW** [comment]
@waitfortea 你的网络问题

**Comment by waitfortea** [comment]
奇怪的是为什么同样的网络环境 3.8可以呢

**Comment by WXRIW** [comment]
@waitfortea 3.8你登录没，建议加群细聊

**Comment by waitfortea** [comment]
不管我开不开外网，登录都可以，但是都无法获取歌词

**Comment by waitfortea** [comment]
> 

可以登录

**Comment by WXRIW** [comment]
@waitfortea 登录后能不能获取播放状态

**Comment by waitfortea** [comment]
就是登录后无法获取播放状态 4的话，群的话是telegram的吗

**Comment by WXRIW** [comment]
@waitfortea tg，qq都可
