### ISSUE TITLE
【歌词】无法正常获取歌词

### ISSUE THREAD

**Issue by LITDARK** [WXRIW/Lyricify-App#141]
今日照常听歌，发现最近新加入歌单的歌曲未自动获取到歌词，于是进入手动管理导入歌词
点击QQ音乐的Mid导入歌词确定后导入按钮变灰，无法继续点击，也没有获取到歌词
在`%AppData%\Roaming\Lyricify\Lyricify for Spotify\Log.txt`中发现如下错误：
```
2023-05-18T04:10:50.5086399+08:00 [Error] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at QQMusicDecoder.DESHelper.IP(UInt32[] state, Byte[] input)
   at QQMusicDecoder.DESHelper.Crypt(Byte[] input, Byte[] output, Byte[][] key)
   at QQMusicDecoder.DESHelper.TripleDESCrypt(Byte[] input, Byte[] output, Byte[][][] key)
   at QQMusicDecoder.Decrypter.DecryptLyrics(String encryptedLyrics)
   at QQMusicDecoder.Helper.GetLyricsAsync(String id)
   at Lyricify_for_Spotify.Windows.TrackManagement.tEr0rs86T7(Object  , RoutedEventArgs  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```
同时`%AppData%\Roaming\Lyricify\Lyricify for Spotify\Log.Lyrics.txt`中有如下错误：
```
2023-05-18T04:10:50.1535236+08:00 [Trace] Get QQ Lyrics - 002eHwrJ2bJAas - 372256475 - Enter
2023-05-18T04:10:50.2803077+08:00 [Error] GetLrcFile - Unknown tag [00:08:73]
2023-05-18T04:10:50.2807299+08:00 [Error] GetLrcFile - After LyricsLrcSimpleFix - Unknown tag [00:08:73]
2023-05-18T04:10:50.2810554+08:00 [Error] GetLrcFile - Unknown tag [00:08:73]
2023-05-18T04:10:50.2813644+08:00 [Error] GetLrcFile - After LyricsLrcSimpleFix - Unknown tag [00:08:73]
......(此处忽略相同错误)
2023-05-18T04:10:50.3233218+08:00 [Error] GetLrcFile - Unknown tag [04:23:74]
2023-05-18T04:10:50.3235872+08:00 [Error] GetLrcFile - After LyricsLrcSimpleFix - Unknown tag [04:23:74]
2023-05-18T04:10:50.4606973+08:00 [Error] Get QQ Verbatim Lyrics (Place 1) - 002eHwrJ2bJAas - 372256475 - Index was outside the bounds of the array.
```
通过网易云音乐歌曲id导入歌词确定后导入按钮变绿，但仅获取到了词曲作者信息，无实际歌词
两个Log文件内也无错误产生

但该歌曲在上述两个平台的客户端中歌词均正常显示且可滚动

应该不是网络原因，移动和联通网络以及对应加梯子都会产生错误
怀疑可能是源歌词格式问题？

产生错误的歌曲信息如下
歌名 `PERSONA`
艺人 `rejection, PANXI`
专辑 `PERSONA`
Spotify ID `03Szw29ysTw888bMThsro3`
QQ音乐歌曲MID `002eHwrJ2bJAas`
网易云音乐歌曲ID `1973975964`

**Comment by WXRIW** [comment]
@LITDARK 反馈收到。很优秀的反馈！👍

**Comment by WXRIW** [comment]
## 已经查到了相关原因
### 变灰后无法继续点击的问题
由与这首歌的没有逐字歌词，所以逐字接口返回为空，在处理时异常，故出现了这个问题。目前已经修复，将在下一版推送。
### QQ 音乐歌词
这首歌在 QQ 音乐是有逐行歌词的，但是经检查，歌词不符合 LRC 标准
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/7a41c8fe-7caa-4960-9d07-903be1290fbe)
这是一部分歌词原始文本，LRC 标准要求时间轴格式为 [mm:ss.fff]，但是这部分歌词的时间轴格式是 [mm:ss:fff]，故无法正常反序列化。
### 网易云音乐歌词
无法正常显示的原因同上
![image](https://github.com/WXRIW/Lyricify-App/assets/62491584/3da6bbe3-bb91-4a2b-87db-d0d27a59b484)
只有前两行是符合标准的，所以只显示了前两行的歌词。

**Comment by LITDARK** [comment]
感谢回复！
>LRC 标准要求时间轴格式为 [mm:ss.fff]，但是这部分歌词的时间轴格式是 [mm:ss:fff]，故无法正常反序列化。

对于这种原平台里的非标歌词，能否直接让用户进行手动上传？

**Comment by WXRIW** [comment]
@LITDARK 这种特殊情况是允许在 Lyricify 歌词库上传正确歌词而不被封号的

**Comment by LITDARK** [comment]
明白了，感谢解答！

**Comment by WXRIW** [comment]
问题已解决，Issue 关闭
