### ISSUE TITLE
在Windows上使用一段时间后会闪退

### ISSUE THREAD

**Issue by BnqDzj** [WXRIW/Lyricify-App#183]
在Windows上使用一段时间后会闪退
系统 Windows 11 22H2 X64
OS组建 22621.2361

日志文件 [Log.txt](https://github.com/WXRIW/Lyricify-App/files/12804059/Log.txt)

System.NullReferenceException: Object reference not set to an instance of an object.
   at (Object , String , String )
   at bgupWj4sC8Dfp86Ypy25.I4V4FrHcof1(Object , String , String , bgupWj4sC8Dfp86Ypy25 )
   at Lyricify_for_Spotify.Tools.Apple_Music.AppleMusicWrittenByLine..ctor(String writers, Int32 line)
   at Lyricify_for_Spotify.Pages.AppleMusic.PageAppleMusicLyrics.<>c__DisplayClass46_0.PCl1JI4HdKcrQxOP397S.MoveNext()
--- End of stack trace from previous location ---
   at GYIJpa4BdpiIbHPvCIw4.I4V4FrHcof1(TaskAwaiter& , GYIJpa4BdpiIbHPvCIw4 )
   at Lyricify_for_Spotify.Pages.AppleMusic.PageAppleMusicLyrics.zcFgAyXqOf(Object  , ElapsedEventArgs  )
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by WXRIW** [comment]
我也遇到过类似的崩溃问题，将在了解到更多细节信息后修复，等待后续新版本即可。
此 Issue 暂时关闭，感谢反馈。
