### ISSUE TITLE
【求助】无法导入非长非长长的歌词

### ISSUE THREAD

**Issue by lwjlwjlwjlwj** [WXRIW/Lyricify-App#274]
【说明】
本来是想把薛之谦演唱会的全程音频弄下来做个全程的歌词，当制作完后，发现长达1000多行的歌词导入后不生效（有时会直接保存不了）。目前测试下来发现900行以内是正常的，现在想知道这是bug还是我个人的电脑原因，下面我提供了音频来源和歌词文件。

【报错信息】
2024-02-25T23:16:39.5782420+08:00 [Trace] System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s)
   at iuO475pELqiCjC4nfYWQ.cfbpgu3iBfB(String , iuO475pELqiCjC4nfYWQ )
   at Lyricify_for_Spotify.LyricsHelpers.VerbatimLyrics..ctor(String content)
2024-02-25T23:16:39.5786830+08:00 [Error] Get Lyricify Lyrics  - Value was either too large or too small for an Int32.
2024-02-25T23:16:47.3365633+08:00 [Trace] System.OverflowException: Value was either too large or too small for an Int32.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Int32.Parse(String s)
   at iuO475pELqiCjC4nfYWQ.cfbpgu3iBfB(String , iuO475pELqiCjC4nfYWQ )
   at Lyricify_for_Spotify.LyricsHelpers.VerbatimLyrics..ctor(String content)
2024-02-25T23:16:47.3370100+08:00 [Error] Get Lyricify Lyrics  - Value was either too large or too small for an Int32.

【音频来源】
https://www.bilibili.com/video/BV1g64y1n79p

【歌词文件】
链接：https://pan.baidu.com/s/12mNeYBmxdTSxRWxYdEsBhw?pwd=zp5r 
提取码：zp5r

**Comment by WXRIW** [comment]
歌词有问题。

第 937 行：
`[4]你(8554842,4294967089)喜(8554635,335)欢(8554970,335)的(8555305,335)我(8555643,462)都(8556105,366)尝(8556471,366)试(8556838,637)过 (8557475,886)狼(8562623,378)狈(8563001,378)的(8563379,378)样(8563758,479)子(8564237,479)你(8564716,340)是(8565056,340)否(8565396,340)听(8565738,477)说(8566215,1199)`

其中，4294967089 超出了 Int32 的范围，是错误的数值。

**Comment by lwjlwjlwjlwj** [comment]
感谢~，早点休息哦
