### ISSUE TITLE
没有自动隐藏灵动词岛

### ISSUE THREAD

**Issue by jsdfhasuh** [WXRIW/Lyricify-App#321]
![image](https://github.com/WXRIW/Lyricify-App/assets/49879362/4d5d9fdc-9bb5-4582-852e-fa3d250c0f43)
![image](https://github.com/WXRIW/Lyricify-App/assets/49879362/700f5e2c-7cba-4e8f-8399-e39679def1ee)
没有播放的时候，没有隐藏

**Comment by WXRIW** [comment]
我无法复现出该问题。
请提供详细的复现方法以供进一步调查。

**Comment by jsdfhasuh** [comment]
日志：
2024-04-25T21:46:56.2954201+08:00 [Trace] Get QQ Lyrics - 003y38qH0uKz8C - 649222 - Enter
2024-04-25T21:46:56.2986958+08:00 [Trace] Get QQ Lyrics - 001PLxlL4Xd37G - 861327 - Enter
2024-04-25T21:46:56.3611246+08:00 [Trace] Process QQ Lyrics - 003y38qH0uKz8C - Enter
2024-04-25T21:46:56.3637963+08:00 [Event] Get QQ Lyrics - 003y38qH0uKz8C - Ready
2024-04-25T21:46:56.3645807+08:00 [Event] Get QQ Lyrics - 003y38qH0uKz8C - Ready
2024-04-25T21:46:56.3722991+08:00 [Trace] Process QQ Lyrics - 001PLxlL4Xd37G - Enter
2024-04-25T21:46:56.3758405+08:00 [Event] Get QQ Lyrics - 001PLxlL4Xd37G - Ready
2024-04-25T21:46:56.3773595+08:00 [Event] Get QQ Lyrics - 001PLxlL4Xd37G - Ready

**Comment by jsdfhasuh** [comment]
软件日志：
2024-04-25T21:47:33.4310069+08:00 [Error] System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Lyricify_for_Spotify.Windows.DynamicLyricsIsland.pq2qNbp5oE()
   at Lyricify_for_Spotify.Windows.DynamicLyricsIsland.<>c__DisplayClass7_0.rcvcdebIOlIC9Nevvipy.MoveNext()
   --- End of inner exception stack trace ---
2024-04-25T21:47:35.6370339+08:00 [Error] System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Lyricify_for_Spotify.Windows.DynamicLyricsIsland.pq2qNbp5oE()
   at Lyricify_for_Spotify.Windows.DynamicLyricsIsland.<>c__DisplayClass7_0.rcvcdebIOlIC9Nevvipy.MoveNext()
   --- End of inner exception stack trace ---
2024-04-25T21:47:37.8780161+08:00 [Error] System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Lyricify_for_Spotify.Windows.DynamicLyricsIsland.pq2qNbp5oE()
   at Lyricify_for_Spotify.Windows.DynamicLyricsIsland.<>c__DisplayClass7_0.rcvcdebIOlIC9Nevvipy.MoveNext()
   --- End of inner exception stack trace ---
2024-04-25T21:49:42.7118939+08:00 [Error] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Lyricify_for_Spotify.Windows.DynamicLyricsIsland.pq2qNbp5oE()
   at Lyricify_for_Spotify.Windows.DynamicLyricsIsland.KpwqAI0wfV(Object  , MouseEventArgs  )
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-04-25T21:49:45.2089335+08:00 [Error] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Lyricify_for_Spotify.Windows.DynamicLyricsIsland.pq2qNbp5oE()
   at Lyricify_for_Spotify.Windows.DynamicLyricsIsland.KpwqAI0wfV(Object  , MouseEventArgs  )
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-04-25T21:49:45.9552627+08:00 [Error] System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Lyricify_for_Spotify.Windows.DynamicLyricsIsland.pq2qNbp5oE()
   at Lyricify_for_Spotify.Windows.DynamicLyricsIsland.KpwqAI0wfV(Object  , MouseEventArgs  )
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by jsdfhasuh** [comment]
> 这个日志没有参考价值的。现在需要你做的是描述如何产生你表达的异常情况。最好同时提供录屏。

如何提供录屏。现在是打开软件就会这个情况，不需要播放

**Comment by WXRIW** [comment]
提供从打开软件开始的录屏。有助于我定位问题。

**Comment by jsdfhasuh** [comment]
录屏
https://github.com/WXRIW/Lyricify-App/assets/49879362/9cb56959-1afb-49c0-a6d8-6e6e2607b92f



> 提供从打开软件开始的录屏。有助于我定位问题。

**Comment by WXRIW** [comment]
关闭灵动词岛并重新开启后，看看能否恢复。
关闭 Lyricify 并重新打开，点击播放，再暂停，看看能否恢复。
最好提供这两个操作过程的录屏。

**Comment by jsdfhasuh** [comment]
> 
关闭灵动词岛并重新开启后，看看能否恢复。 关闭 Lyricify 并重新打开，点击播放，再暂停，看看能否恢复。 最好提供这两个操作过程的录屏。




Uploading 关闭 Lyricify 并重新打开，点击播放，再暂停.mp4…

https://github.com/WXRIW/Lyricify-App/assets/49879362/31106497-01d7-496c-a4ae-28c02a006dff

关闭灵动词岛并重新开启：
https://github.com/WXRIW/Lyricify-App/assets/49879362/6f1ab4aa-dbf7-43bd-a0db-344204136dd7

**Comment by WXRIW** [comment]
你没有测试：关闭 Lyricify 并重新打开，点击播放，再暂停，看看能否恢复。
还有就是操作过程中不要最小化 Lyricify 主窗体，这会影响做出判断。

**Comment by jsdfhasuh** [comment]
> 你没有测试：关闭 Lyricify 并重新打开，点击播放，再暂停，看看能否恢复。 还有就是操作过程中不要最小化 Lyricify 主窗体，这会影响做出判断。


https://github.com/WXRIW/Lyricify-App/assets/49879362/806df9f4-d01b-41ce-92af-2b0bd3c8d4a7

看看是否有问题

**Comment by WXRIW** [comment]
你是有多个显示器吗？是怎样的配置。

**Comment by jsdfhasuh** [comment]
> 你是有多个显示器吗？是怎样的配置。

Lyricify显示的屏幕是二号屏幕，作为主屏幕

**Comment by WXRIW** [comment]
经检查，确实是多屏造成的。
已修复，将随下一版本更新发布。

**Comment by WXRIW** [comment]
经检查，确实是多屏造成的。
已修复，将随下一版本更新发布。
