### ISSUE TITLE
Lyricify Lite windows商店版本经常查不到歌词

### ISSUE THREAD

**Issue by SwiftVwing** [WXRIW/Lyricify-App#426]
hello, Lyricify 4一切正常，换了Lite后经常到下首歌后卡住，手动刷新歌词也得好几次才能查到。
![image](https://github.com/user-attachments/assets/5ab189f5-e94c-4734-8031-3bb1536048ef)

2024-12-17T12:00:39.6118426+08:00 [Info] [Search Track] [QQ Music] Cassandra (Explicit) • Taylor Swift • THE TORTURED POETS DEPARTMENT: THE ANTHOLOGY (Explicit) •  • Perfect • 0014Ezd23QhDmw
2024-12-17T12:00:40.8305726+08:00 [Error] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: 远程主机强迫关闭了一个现有的连接。.
 ---> System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Lyricify.Lyrics.Providers.Web.BaseApi.PostAsync(String url, Dictionary`2 paramDict)
   at Lyricify.Lyrics.Providers.Web.QQMusic.Api.GetLyricsAsync(String id)
   at VJ9qeRxFksQaBGVGyYq.X3vSymx5moVKCXXP1Ln.zqLxJwLTo7(Object  )

**Comment by WXRIW** [comment]
从日志上看，是你的网络问题。网络不好，所以出现了 SSL 错误。

**Comment by WXRIW** [comment]
btw，Lyricify Lite 主要是给非 Spotify 用户准备的，一般来说建议 Spotify 用户使用 Lyricify 4 获取完整体验，包括更完善的歌词库等。

**Comment by SwiftVwing** [comment]
我这工作环境网确实不太好，不过Lirycify 4一直是好的，这个有什么区别吗？
切换到lite是因为一般只用灵动词岛，而且更主要的是开机自启比较方便，4的话我每次得先梯子开全局才能登录成功，完了再切回rule，嫌麻烦。。。

**Comment by WXRIW** [comment]
@SwiftVwing 那一定是分流没分好，确保 spotify.com 全部走海外流量就不会出问题了。Lyricify 4 的词库比 Lite 强大很多，具有完整的一套词库管理系统，而 Lite 的歌词都是当场搜，匹配率也会低一点。

**Comment by SwiftVwing** [comment]
@WXRIW 好的，那我改下规则，继续用4吧，感谢
